"""
Django settings for easybio project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from .base import *
from pathlib import Path
import os


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-50hi_kaa#)qxstv(yh#j3$012v@_zqu7!hmr@%n@ph=zlt1gdq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']



# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
        'default': {
            'ENGINE':'djongo',
            'NAME':'easybiodb',
            'ENFORCE_SCHEMA': True,
            'CLIENT': {
                'host': 'mongodb://easybiousr:ClaveEasyBio2023@localhost:27017'
            }             
        }
}

